language: node_js
node_js:
  - "node"
deploy:
  api_key:
    secure: BRfiOImQZaXmhwvUdUQ5UQI5jWHi7I5upLjiGmwiWzFRwM2bHzz7WcFcZf0wtj1JElQzFUQAmiJ01b1FcooXyYXbrEXqUKs1R1dNwYXGzAH12/xunA+ufeEGNHynVj9WN/SmxW7Tx5KqA1hlO0BGhZGIOQ7arEnaKwUgbUpjB8TSpDrNd6JIu2cOfhLk9dvVmsqlJP5vYjnDx+G0O4+s5K+02MHAg36dcgX77fgPwz1KnTios7e4/poSlSiFPXQmWq54okYdK0YpkI7et6DedWZ1BxxH+fpbOMgnIqPRpt6v206g2IuzjxjxyrxSmnFZ39mQiqrW5VjcOoQRdFS8Ve9ngMH/X9Hix0ldzsKMOkho3P1Ncd10qPKb4qjVZ8sRefy0oTziZNB4E4pkTW/+O/AqfMEANdZxwRy5uQyteYv/ULFKWPd3R1s0gj4mBndRSZxL3AsfdOrDtYZ0Dor44x6e2541CbykGF6EUV+5a8K1M9g+kLS+nKx0Lrps+TG+frGaqj9nJdoGPcCmpulCQAt3Wu6edlCYrbSuHt2mmFLOzYUzzTIo1OTrTbvZq1SMCYHZPCAnB6UshjK0/tRWVn3j5EQlwUuvv+1K4kABuNdlc96yOSW5ARl4cEbNsIo7JPKHowo2LE0WSYeMI5YuXInwlSVhg7rIzkspRsfrRGg=
  email: lotosbin@gmail.com
  provider: npm
